### ISSUE TITLE
Unable to set clustering_order option

### ISSUE THREAD

**Issue by sskorol** [ifaim/nestjs-express-cassandra#9]
## I'm submitting a...

 - [ ] Regression
 - [x] Bug report
 - [ ] Feature request
 - [ ] Documentation issue or request

## Current behavior
`clustering_order` option forces using all the keys specified within `key` array. As a result, if we specify only a clustering key, it fails on compilation step with the following error:
```text
 No overload matches this call.
  Overload 2 of 2, '(name?: string, options?: EntityOptions<any>): ClassDecorator', gave the following error.
    Argument of type '{ table_name: string; key: (string | string[])[]; clustering_order: { createdAt: string; }; }' is not assignable to parameter of type 'string'.
```
When we specify all keys from within `key` option, compilation fails as well with the following error:
```text
apollo.model.validator.invalidschema: clustering_order field attributes must be clustering keys only
    at f (/XXX/node_modules/express-cassandra/lib/orm/apollo_error.js:177:15)
    at Object.addModel (/XXX/node_modules/express-cassandra/lib/orm/apollo.js:470:13)
    at f [as loadSchema] (/XXX/node_modules/express-cassandra/lib/expressCassandra.js:186:44)
    at Object.loadModel (/XXX/node_modules/@iaminfinity/express-cassandra/dist/orm/utils/model.utils.js:17:30)
    at /XXX/node_modules/@iaminfinity/express-cassandra/dist/express-cassandra.providers.js:20:51
    at Observable._subscribe (/XXX/node_modules/rxjs/internal/observable/defer.js:10:21)
    at Observable._trySubscribe (/XXX/node_modules/rxjs/internal/Observable.js:44:25)
    at Observable.subscribe (/XXX/node_modules/rxjs/internal/Observable.js:30:22)
    at /XXX/node_modules/rxjs/internal/Observable.js:99:19
    at new Promise (<anonymous>)
    at Observable.toPromise (/XXX/node_modules/rxjs/internal/Observable.js:97:16)
    at Object.<anonymous> (/XXX/node_modules/@iaminfinity/express-cassandra/dist/express-cassandra.providers.js:20:86)
    at Generator.next (<anonymous>)
    at /XXX/node_modules/@iaminfinity/express-cassandra/dist/express-cassandra.providers.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/XXX/node_modules/@iaminfinity/express-cassandra/dist/express-cassandra.providers.js:3:12)
```

## Expected behavior
`clustering_order` option should allow using only clustering keys from within `key` array.

## Minimal reproduction of the problem with instructions
```typescript
import { Column, CreateDateColumn, Entity, UpdateDateColumn } from '@iaminfinity/express-cassandra'

@Entity({
  table_name: 'state_per_device',
  key: [['deviceId'], 'createdAt'],
  clustering_order: { createdAt: 'desc' } // is not allowed; deviceId should be specified as well; but as it's a primary key, it fails
})
export class DeviceState {
  @Column({ type: 'uuid' })
  public deviceId: any

  @CreateDateColumn()
  public createdAt: Date

  @UpdateDateColumn()
  public updatedAt: Date

  @Column({ type: 'blob' })
  public execution: Buffer
}
```

## What is the motivation / use case for changing the behavior?
Allow users to customize clustering order.

## Environment

- Nest version: 6.8.0
- Node version: 12.9.1
- Platform:  Mac

**Comment by ifaim** [comment]
This is TypeError, please try like this.
```
import { Column, CreateDateColumn, Entity, UpdateDateColumn } from '@iaminfinity/express-cassandra'

@Entity<DeviceState>({
  table_name: 'state_per_device',
  key: [['deviceId'], 'createdAt'],
  clustering_order: { createdAt: 'desc' } // is not allowed; deviceId should be specified as well; but as it's a primary key, it fails
})
export class DeviceState {
  @Column({ type: 'uuid' })
  public deviceId: any

  @CreateDateColumn()
  public createdAt: Date

  @UpdateDateColumn()
  public updatedAt: Date

  @Column({ type: 'blob' })
  public execution: Buffer
}
```

**Comment by sskorol** [comment]
Yup, generic type specification on Entity level did the trick. Thanks!
